language: elixir
elixir:
    - 1.3.4
    - 1.4.5
    - 1.5.3
    - 1.6.6
otp_release:
    - 19.3.6
    - 20.3.8

matrix:
  exclude:
    - elixir: 1.3.4
      otp_release: 20.3.8
  include:
    - elixir: 1.6.6
      otp_release: 21.0.3
    - elixir: 1.6.6
      otp_release: 20.3.8
      script: mix format --check-formatted
